process-engine/process_engine_core_meta

- .gitignore
- .meta
- setup.sh
This branch contains the following changes:
- added the bootstrapper_browser package to the meta file
- removed the `feature/namespaces_versioning_fixes`-branch usage
- added install and build for process-engine-browser
> :sparkles: add bootstrapper_browser

- Jenkinsfile_TEMPLATE
This PR adds the Jenkinsfile_TEMPLATE. This file need to be added to all repositories, this should be done _after_ this PR is merged. @heikomat has some scripts for that. Also we need to adjust the `scripts` section in the `package.json` files.
Currently the Jenkinsfile doesnt publishes packages to npm. I would suggest to add this functionality later, as this requires additional configuration on jenkins.
In Jenkins I installed the `nodejs` plugin to provide nodejs. The Jenkinsfile uses `node-v7` as tool description, this is configured under the global tools configuration in jenkins.
> ✨ Add Jenkinsfile_TEMPLATE

- _templates/gulpfile.js
- _templates/gulpfile_commonjs_only.js
This adds `suppressErrorsForTasks: ['lint']`. 
This will no longer cause linting messages to cuase errors.
n/a
> 🚨 Disabsle linting errors in templates

- _templates/Jenkinsfile
- _templates/Jenkinsfile-node-v7
Adds 1 new jenkinsfile to test node v7 and sets the node version in default jenkinsfile to node v8
> 👷 Add Jenkinsfile for LTS and Node v7

- _templates/Jenkinsfile
Now when Jenkins runs the Pipeline and the current branch is master,
it will publish the npm package to the registry.
The token for publishing is configured in Jenkins.
n/a
> 👷 Add Publish Stage to Jenkinsfile

- meta_examples.md
Adds example scripts to update Jenkinsfiles
n/a
> 📝 Add Scripts to Update Jenkinsfiles

- LICENSE
- _templates/LICENSE_MIT
- meta_examples.md
1. Add a suitable license.
1. Cleanup meta_examples.sh
View the LICENSE-file; it should contain the MIT license.
Review the meta_examples.sh.
> Add MIT License

- package.json
I updated the version of minstall that is used by meta to `^3.0.3`. This should not change any usage or behaviour
run the setup and see if it still works as it does in develop
> ⬆️ update minstall version to ^3.0.3

- .gitignore
- .meta
- _sample_scripts/update_to_1.0.0-rc1.sh
- meta_examples.md
- setup.sh
- ⏰ Waits on https://github.com/process-engine/charon/pull/132
- ✅ Fixes https://github.com/process-engine/charon/issues/131
- ~~🔜 Skeleton https://github.com/process-engine/skeleton/pull/27~~
- 🔜 documentation https://github.com/process-engine/documentation/pull/63
- 🔜 consumer_client https://github.com/process-engine/consumer_client/pull/13
- Checkout 
- setup
> 🚧 🚚 :truck: Rename Charon to BPMN-Studio

- .gitignore
`http_integration_testing` was missing in `.gitignore`
`http_integration_testing` was always untracked.
> 🐛 :bug: Add http_integration_testing to .gitignore

- _templates/Jenkinsfile
The build now fails if the version is a rc version
n/a
> 👷 :construction_worker: Fail on rc Versions in Master

- _templates/Jenkinsfile
- _templates/Jenkinsfile-node-v7
All Builds are now Published to npm
> 👷 :construction_worker: Publish all Builds to npm Registry

- _templates/Jenkinsfile
This *should* result in Jenkins only trying to publish from master, IF the version changed. I had no repository with a published package available to test this.
The result would be, that the Jenkins doesn't fail every night when trying to publish updates
Even i couldn't test the changes. We should critically inspect the code and see if it should work. We'll see this in the next release
> 🐛 Only Publish Package if Version Changed

- _templates/Jenkinsfile
- _templates/Jenkinsfile-node-v7
> :art: Extract Cleanup Workspace in Function

- _templates/Jenkinsfile
- _templates/Jenkinsfile-node-v7
> :art: Remove Superfluous Comment

- .gitignore
- .meta
- setup.sh
> ✨ :sparkles: Add tslint-config And bpmn-io_custom-bundle

- .meta
> Describe the changes introduced by this PR.
>
> Fixes # (issue, if applicable)
> ✨ Add datasource_adapter_localstorage to .meta file

- _templates/Jenkinsfile
Fixes issues with newlines in jenkinsfile
> :bug: Add Missing .trim() in Jenkinsfile

- .gitignore
- .meta
Rename consumer_client to bpmn-studio_client
> :truck: Rename consumer_client to bpmn-studio_client

- _sample_scripts/update_to_1.0.0.sh
> :wrench: Add Scripts for Release of 1.0.0

- Jenkinsfile
- _integration_tests/package.json
After this PR the jenkins will display any changes in the `Tests` tab on the build page:
Visit http://ci.process-engine.io:8080/job/process-engine_node-lts/job/process_engine_meta/job/feature%252Fadd_test_result_reporter/
> :construction_worker: Add Test Reports to Jenkins Tests View

- _integration_tests/bpmn/terminate_end_event_sample.bpmn
Fix timer type declaration in sample process for the `TerminateEndEvent` test.
Run the test.
> Fix sample process for terminate end event test

- .gitignore
- .jsbeautifyrc
- _integration_tests/bpmn/nested_xor.bpmn
- _integration_tests/bpmn/simple_xor_gateway_test.bpmn
- _integration_tests/bpmn/xor_evaluate_script_result.bpmn
- _integration_tests/ioc_module.js
- _integration_tests/test/nested_xor.js
- _integration_tests/test/parse_bpmn_model_to_object_model.js
- _integration_tests/test/simple_xor_gateway_test.js
- _integration_tests/test/xor_evaluate_script_result.js
I implemented some tests for xor gateway.
By running `npm test` in the `_integrationTests` folder.
> [WIP] Feature/int test xor gateway

- Jenkinsfile
See https://github.com/process-engine/skeleton/pull/57/
See jenkins build https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fskeleton/detail/feature%2Fignore_docker_cleanup_failures/4/pipeline/
> 👷 Ignore Failures of Docker Cleanup

- Jenkinsfile
- Add a timeout to while loop
Fixes #87 
> 👷 Add Timeout to while Loop

- README.md
This PR restructures the structure of the readme on the meta repository.
> [WIP] Restructure Readme on the meta repsitory

- _integration_tests/bpmn/error_end_event_call_activity_called_process.bpmn
- _integration_tests/bpmn/error_end_event_subprocess_call_activity_test.bpmn
- _integration_tests/bpmn/error_end_event_test.bpmn
- _integration_tests/test/error_end_event_test.js
Closes #81 
This PR implements Integration tests for the error end event.
Run `npm test` in the _integration_tests directory.
> Integration tests for the error end event

- _integration_tests/package.json
- _integration_tests/test/boundary_event_timer_test.js
Fixes #101 
This PR fixes the failing Integration Tests on the **master branch**.
Run `npm test`
> Fix integration tests

- Jenkinsfile
Use groovy to extract build results instead of relying on grep.
Checkout the builds
> 👷 :construction_worker: More Robust Result Parsing

- Jenkinsfile
With the former test timeout of `60000` milliseconds, the tests kept failing more often than they worked.
With the test timeout increased to `120000` milliseconds, the tests have not failed yet.
* Run the integration tests.
* All tests should pass.
> Increase test timeout to fix tests

- _templates/Jenkinsfile
:tada: **Thanks for submitting this Pull Request**
Please provide a list including your changes.
To help us to create a meaningful Changelog, we agreed
to use an emoji-based commit-style. Use the [Emojis](#emojis)
we provided below.
Fill out the following, provide reference to issues
and this PR- we will use this as merge commit message-body
and the title of this PR as commit-headline:
---
**Changes:**
1. Publish to npm even if last build failed.
2. Add message explaining why the build was not published. 
**Issues:**
See process-engine/bpmn-studio#899
PR: #132
---
See the [examples](#example) for inspiration.
n/a
Also see process-engine/bpmn-studio#900
<details>
<summary>
:warning: Before merging please click here to expand and …
> :construction_worker: Publish On Retry if Previous Failed

- _integration_tests/package.json
- _integration_tests/test/end_events.js
- _integration_tests/test/interprocess_communication_test.js
- _integration_tests/test/start_event_tests.js
Requires:
https://github.com/process-engine/process_engine_contracts/pull/74
https://github.com/process-engine/process_engine_core/pull/186
**Changes:**
1. Update `ProcessEngineCore`.
2. Update tests related to the handling of messages and signals. 
PR: #148
Run the tests.
<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>
To get your commit message, just copy the first part of this pull request.
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at ...
- Fixes …
> ♻️ Use name of signals and messages

- _templates/Jenkinsfile
**Changes:**
1. Archive package-lock.json file
**Issues:**
PR: #155 
---
See the [examples](#example) for inspiration.
<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>
To get your commit message, just copy the first part of this pull request.
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: …
> :construction_worker: Archive package-lock.json After Installing

- _integration_tests/package.json
---
**Changes:**
1. Fixes the current versioning in the `package.json`, where the version for the ProcessEngineCore packet still points to the feature branch for the timer defintion validation.
**Issues:**
PR: #169
---
See the [examples](#example) for inspiration.
<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>
To get your commit message, just copy the first part of this pull request. …
> 🐛 Use the Correct Semver Version for the ProcessEngineCore Package

- _integration_tests/bpmn/user_task_test.bpmn
- _integration_tests/package.json
- _integration_tests/src/fixture_providers/test_fixture_provider.ts
- _integration_tests/test/user_task_tests.js
**Changes:**
1. Add test for validating UserTasks with invalid FormField configurations.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/240
Part of https://github.com/process-engine/process_engine_runtime/issues/263
PR: #179
Run the tests.
> 🔒 ♻️ Validate UserTask payloads

- _integration_tests/package.json
- _integration_tests/test/error_end_event_test.js
**Changes:**
1. Update to mocha v6.
2. Implement the fix for CallActivity ProcessTermination from the [ProcessEngineCore package](https://github.com/process-engine/process_engine_core/pull/260).
PR: #185
Run the tests.
> ✨ CallActivity termination

- _integration_tests/bpmn/intermediate_event_receive_tests.bpmn
- _integration_tests/bpmn/intermediate_event_send_tests.bpmn
- _integration_tests/package.json
- _integration_tests/test/interprocess_communication_test.js
**Changes:**
Add tests for covering MessageEvents and SignalEvents with a customized payload.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/296
PR: #186
Run the tests.
> ✨ Allow for customized event payloads

- _integration_tests/package.json
Update `ProcessEngineCore` to fix FlowNodeInstance resumption.
Part of https://github.com/process-engine/process_engine_runtime/issues/332
PR: #199
Run the tests.
> 🐛 Fix resumption of FlowNodes with multiple FlowNodeInstances

- _integration_tests/package.json
1. Update ProcessEngineCore (See: https://github.com/process-engine/process_engine_core/pull/292)
PR: #207
> ♻️ Improve TimerFacade and TimerDefinition parsing
